export const GET_COUNTRY = "GET_COUNTRY"
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS"
export const GET_COUNTRY_FAILED = "GET_COUNTRY_FAILED"

export const ADD_COUNTRY = "ADD_COUNTRY"
export const ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS"
export const ADD_COUNTRY_FAILED = "ADD_COUNTRY_FAILED"