export const PAYMENT_PENDING = "PAYMENT_PENDING"
export const PAYMENT_PENDING_REMOVE = "PAYMENT_PENDING_REMOVE"

export const PAYMENT = "PAYMENT"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAILED = "PAYMENT_FAILED"

export const GET_TRANSACTION = "GET_TRANSACTION"
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS"
export const GET_TRANSACTION_FAILED = "GET_TRANSACTION_FAILED"

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS"
export const UPDATE_TRANSACTION_FAILED = "UPDATE_TRANSACTION_FAILED"