export const PAYMENT_PENDING = "PAYMENT_PENDING"
export const PAYMENT_PENDING_REMOVE = "PAYMENT_PENDING_REMOVE"

export const PAYMENT = "PAYMENT"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAILED = "PAYMENT_FAILED"

